version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  linting:
    executor: python
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python3-venv
      - run:
          name: Linting
          command:  |
            make setup
            . .env/bin/activate
            make install
            make lint

  building:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: |
            docker login -u ${DOCKER_ID} -p ${DOCKER_PWD}
            docker build --tag flask-app .
      - run:
          name: Pushing Docker Image to Docker Hub
          command:  |
            docker tag flask-app:latest akshtrikha/flask-app:latest
            docker push akshtrikha/flask-app:latest
  
  creating-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          flask-app
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment-config.yml
          resource-name: deployment/flask-app

  testing-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          flask-app
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Getting Data
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment

workflows:
  deploy:
    jobs:
      - linting
      - building:
          requires: [linting]
      - aws-eks/create-cluster:
          cluster-name: flask-app
          requires: [building]
      - creating-deployment:
          cluster-name: flask-app
          requires: [aws-eks/create-cluster]
      - testing-cluster:
          cluster-name: flask-app
          requires: [creating-deployment]
      - aws-eks/delete-cluster:
          cluster-name: flask-app
          requires:
            - testing-cluster